### some ubuntu defaults ###

. ~/.bash_ubuntu

### prefix ###

export _BASH_COMPLETION=/etc/bash_completion



### common ###

source ~/.bash_common



### idealist ###

export PATH="/idealist/sbin:$PATH"
# added by travis gem
[ -f /Users/ericoconnell/.travis/travis.sh ] && source /Users/ericoconnell/.travis/travis.sh
